apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component
  description: My awesome component
  annotations:
    techdocs.io/techdocs-ref: my-component
spec:
  type: service
  owner: myteam
  lifecycle: experimental
  providesApis:
    swagger:
      $ref: 'https://github.com/guruprakashchinnasamy/Backstage_App/blob/main/Backstage_docs/SwaggerInventory.yaml'
  provides:
    techdocs:
      # Optional configuration for the TechDocs plugin
      title: My Component
      description: This is my awesome component
      site_dir: my-component-site
  # Attach the published techdocs output to the component
  relations:
    - type: docs
      target: techdocs:my-component
