name: Generate Markdown from Swagger
on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file
jobs:
  generate-techdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
      #- run: npm ci
      #- run: npm test
      - name: Convert Swagger to Markdown
        uses: actions/github-script@v5
        with:
          script: |
            const { spawn } = require('child_process');
            const swaggerFile = 'Backstage_docs/SwaggerInventory.yaml';
            const outputDir = 'Backstage_docs/testdocs';
            const child = spawn('npx', ['swagger-to-markdown', '-i', swaggerFile, '-o', outputDir]);
            child.on('exit', (code) => {
              if (code === 0) {
                console.log('Swagger to Markdown conversion successful');
                process.exit(0);
              } else {
                console.error(code);
                console.error('Swagger to Markdown conversion failed');
                process.exit(1);
              }
            });
          token: ${{ secrets.GITHUB_TOKEN }}
