name: Swagger to Markdown

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Markdown
      uses: sdelamo/swagger2markup@v3
      with:
        input: https://raw.githubusercontent.com/guruprakashchinnasamy/Backstage_App/main/Backstage_docs/SwaggerInventory.yaml
        outputDir: docs
        output: swagger
        markupLanguage: MARKDOWN
