name: Generate Markdown from Swagger
on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Markdown from Swagger
        uses: gautemo/swagger-to-markdown-action@v1
        with:
          input: guruprakashchinnasamy/Backstage_App/Backstage_docs/SwaggerInventory.yaml # Replace with the path to your Swagger spec file
          output: docs # Replace with the path to your output directory
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Swagger Markdown files"
          commit_options: '--no-verify'
