name: Generate .md files from Swagger

on:
  push:
    branches:
      - main

jobs:
  generate-md:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Generate .md files
        run: npx openapi-generator-cli generate -i https://raw.githubusercontent.com/guruprakashchinnasamy/Backstage_App/main/Backstage_docs/SwaggerInventory.yaml -g markdown -o ./docs

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update .md files from Swagger"
          git push
