name: Swagger to Markdown

on:
  push:
    paths:
      - '**.yamlTest' # Replace with the path to your Swagger spec file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo npm install -g redoc-cli
      - name: Generate Markdown Documentation
        run: |
          redoc-cli bundle https://raw.githubusercontent.com/guruprakashchinnasamy/Backstage_App/main/Backstage_docs/SwaggerInventory.yaml --output=docs/all-apis.html
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Generated Swagger documentation"
          author_name: "Your Name"
          author_email: "your.email@example.com"
          branch: main
          add: "docs/all-apis.html"
          signoff: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTION }}
