name: Swagger to Markdown

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install swagger-markdown

      - name: Convert Swagger to Markdown
        run: npx swagger-markdown -i path/to/swagger.yaml -o path/to/swagger.md
