name: Swagger to Markdown

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install swagger-to-markdown --save-dev
      
      - name: Generate Markdown
        run: npx swagger-to-markdown -i guruprakashchinnasamy/Backstage_App/blob/main/Backstage_docs/SwaggerInventory.yaml -o docs/swagger.md
