name: Generate TechDocs from Swagger

on:
  push:
    paths:
      - '/guruprakashchinnasamy/Backstage_App/Backstage_docs/SwaggerInventory.yaml' # Replace with your Swagger file path

jobs:
  generate-techdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Generate TechDocs
        run: yarn run generate:docs

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update TechDocs from Swagger'
          add: '.backstage/*'
          push: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
