name: Swagger to Markdown using widdershins

on:
  push:
    paths:
      - '**.yaml' # Replace with the path to your Swagger spec file

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -g slate
      - name: Generate documentation
        run: /usr/local/bin/npx slate source Backstage_docs/SwaggerInventory.yaml output Backstage_docs/docs/api/all-apis-slate1.md
      - name: Commit documentation
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update documentation'
          add: '*.md'
          github_token: ${{ secrets.GIT_ACTION }}
